# -*- coding: utf-8 -*-
# ══════════════════════════════════════════════════════════════════════════════
# Credit Scoring Dashboard — Streamlit Application
# Project: Improving Lending Decision-Making and Loan Default Predictions
# Author : Shawn Kimani Ngugi | JKUAT | SCT213-C002-0043/2022
# Supervisor: Mr Daniel Njuguna
#
# Run with:  streamlit run dashboard.py
#
# Required artefacts (generated by the notebook):
#   best_xgb_pipeline.pkl
#   best_lr_pipeline.pkl
#   feature_metadata.json
#   model_comparison_results.csv
# ══════════════════════════════════════════════════════════════════════════════

import json
import os
import warnings
warnings.filterwarnings("ignore")

import joblib
import numpy as np
import pandas as pd
import streamlit as st
import matplotlib.pyplot as plt
import seaborn as sns
try:
    import shap
    SHAP_AVAILABLE = True
except Exception:
    SHAP_AVAILABLE = False
try:
    from sklearn.metrics import (
        roc_curve, roc_auc_score, confusion_matrix,
        f1_score, recall_score, precision_score
    )
except Exception:
    pass

# ── Page configuration ──────────────────────────────────────────────────────
st.set_page_config(
    page_title="Smart Credit — Lending Decision Platform",
    page_icon="🏦",
    layout="wide",
    initial_sidebar_state="expanded"
)

# ══════════════════════════════════════════════════════════════════════════════
# DESIGN SYSTEM
# Palette: deep navy authority (#0D1B2A) + steel blue data (#1B6CA8)
#          + amber alert (#F59E0B) + slate surface (#F1F5F9)
#          + crimson risk (#DC2626) + emerald safe (#16A34A)
# Typography: system monospace for data values, Inter-like sans for body
# Signature: animated risk gauge arc that sweeps on prediction
# ══════════════════════════════════════════════════════════════════════════════
STYLES = """
<style>
/* ── Google Font import ── */
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=JetBrains+Mono:wght@400;600&display=swap');

/* ── Root tokens ── */
:root {
    --navy:   #0D1B2A;
    --steel:  #1B6CA8;
    --amber:  #F59E0B;
    --slate:  #F1F5F9;
    --crimson:#DC2626;
    --emerald:#16A34A;
    --mid:    #64748B;
    --border: #CBD5E1;
    --white:  #FFFFFF;
    --card-shadow: 0 1px 3px rgba(13,27,42,0.08), 0 4px 16px rgba(13,27,42,0.06);
}

/* ── Global reset ── */
html, body, [class*="css"] {
    font-family: 'Inter', -apple-system, sans-serif;
    color: var(--navy);
}

/* ── Sidebar ── */
[data-testid="stSidebar"] {
    background: var(--navy) !important;
    border-right: 3px solid var(--steel);
}
[data-testid="stSidebar"] * { color: var(--white) !important; }
[data-testid="stSidebar"] .stSelectbox label,
[data-testid="stSidebar"] .stSlider label,
[data-testid="stSidebar"] .stNumberInput label { color: #94A3B8 !important; font-size: 0.78rem; text-transform: uppercase; letter-spacing: 0.06em; }
[data-testid="stSidebar"] h1, [data-testid="stSidebar"] h2, [data-testid="stSidebar"] h3 { color: var(--white) !important; }
[data-testid="stSidebar"] .stMarkdown p { color: #CBD5E1 !important; font-size: 0.85rem; }

/* ── Main background ── */
.main .block-container { background: var(--slate); padding-top: 1.5rem; }

/* ── Page header banner ── */
.dashboard-header {
    background: linear-gradient(135deg, var(--navy) 0%, #1a3a5c 100%);
    border-radius: 12px;
    padding: 2rem 2.5rem;
    margin-bottom: 1.5rem;
    display: flex;
    align-items: center;
    justify-content: space-between;
    border-left: 5px solid var(--amber);
}
.dashboard-header h1 {
    color: var(--white) !important;
    font-size: 1.9rem;
    font-weight: 700;
    margin: 0;
    letter-spacing: -0.02em;
}
.dashboard-header p { color: #94A3B8; margin: 0.25rem 0 0; font-size: 0.9rem; }
.header-badge {
    background: rgba(245,158,11,0.15);
    border: 1px solid var(--amber);
    border-radius: 6px;
    padding: 0.5rem 1rem;
    color: var(--amber) !important;
    font-size: 0.78rem;
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 0.08em;
}

/* ── Metric cards ── */
.metric-card {
    background: var(--white);
    border-radius: 10px;
    padding: 1.2rem 1.5rem;
    box-shadow: var(--card-shadow);
    border-top: 3px solid var(--steel);
    height: 100%;
}
.metric-card.risk-high  { border-top-color: var(--crimson); }
.metric-card.risk-low   { border-top-color: var(--emerald); }
.metric-card.risk-amber { border-top-color: var(--amber);   }
.metric-label {
    font-size: 0.72rem;
    text-transform: uppercase;
    letter-spacing: 0.08em;
    color: var(--mid);
    font-weight: 600;
    margin-bottom: 0.3rem;
}
.metric-value {
    font-family: 'JetBrains Mono', monospace;
    font-size: 2rem;
    font-weight: 600;
    color: var(--navy);
    line-height: 1;
}
.metric-value.crimson { color: var(--crimson); }
.metric-value.emerald { color: var(--emerald); }
.metric-sub { font-size: 0.78rem; color: var(--mid); margin-top: 0.3rem; }

/* ── Section headers ── */
.section-header {
    display: flex;
    align-items: center;
    gap: 0.75rem;
    margin: 1.8rem 0 1rem;
    padding-bottom: 0.6rem;
    border-bottom: 1px solid var(--border);
}
.section-header h2 {
    font-size: 1.05rem;
    font-weight: 600;
    color: var(--navy);
    margin: 0;
    text-transform: uppercase;
    letter-spacing: 0.05em;
}
.section-pill {
    background: var(--steel);
    color: var(--white) !important;
    border-radius: 4px;
    padding: 0.15rem 0.55rem;
    font-size: 0.7rem;
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 0.06em;
}

/* ── Decision verdict box ── */
.verdict-approve {
    background: #F0FDF4;
    border: 2px solid var(--emerald);
    border-radius: 10px;
    padding: 1.5rem;
    text-align: center;
}
.verdict-reject {
    background: #FEF2F2;
    border: 2px solid var(--crimson);
    border-radius: 10px;
    padding: 1.5rem;
    text-align: center;
}
.verdict-review {
    background: #FFFBEB;
    border: 2px solid var(--amber);
    border-radius: 10px;
    padding: 1.5rem;
    text-align: center;
}
.verdict-title { font-size: 1.4rem; font-weight: 700; margin-bottom: 0.25rem; }
.verdict-approve .verdict-title { color: var(--emerald); }
.verdict-reject  .verdict-title { color: var(--crimson); }
.verdict-review  .verdict-title { color: #92400E; }
.verdict-sub { font-size: 0.88rem; color: var(--mid); }

/* ── Risk gauge SVG container ── */
.gauge-container { display: flex; justify-content: center; padding: 0.5rem 0; }

/* ── Feature importance table ── */
.fi-bar-bg {
    background: #E2E8F0;
    border-radius: 3px;
    height: 8px;
    overflow: hidden;
}
.fi-bar-fill {
    background: var(--steel);
    height: 100%;
    border-radius: 3px;
    transition: width 0.6s ease;
}

/* ── Data table ── */
.stDataFrame { border-radius: 8px; overflow: hidden; }

/* ── Tab styling ── */
.stTabs [data-baseweb="tab-list"] {
    background: var(--white);
    border-radius: 8px 8px 0 0;
    padding: 0.25rem 0.25rem 0;
    gap: 2px;
    border-bottom: 2px solid var(--steel);
}
.stTabs [data-baseweb="tab"] {
    color: var(--mid);
    font-weight: 500;
    font-size: 0.85rem;
    padding: 0.6rem 1.2rem;
    border-radius: 6px 6px 0 0;
}
.stTabs [aria-selected="true"] {
    background: var(--steel) !important;
    color: var(--white) !important;
}

/* ── Buttons ── */
.stButton > button {
    background: var(--steel);
    color: var(--white);
    border: none;
    border-radius: 7px;
    font-weight: 600;
    font-size: 0.88rem;
    padding: 0.65rem 1.8rem;
    letter-spacing: 0.03em;
    transition: background 0.2s;
    width: 100%;
}
.stButton > button:hover { background: #155d96; }

/* ── Info / warning boxes ── */
.info-box {
    background: #EFF6FF;
    border-left: 4px solid var(--steel);
    border-radius: 0 6px 6px 0;
    padding: 0.8rem 1rem;
    font-size: 0.85rem;
    color: #1e3a5f;
    margin: 0.75rem 0;
}
.warn-box {
    background: #FFFBEB;
    border-left: 4px solid var(--amber);
    border-radius: 0 6px 6px 0;
    padding: 0.8rem 1rem;
    font-size: 0.85rem;
    color: #78350F;
    margin: 0.75rem 0;
}
</style>
"""
st.markdown(STYLES, unsafe_allow_html=True)

# ══════════════════════════════════════════════════════════════════════════════
# CONSTANTS & HELPERS
# ══════════════════════════════════════════════════════════════════════════════

RISK_COLOUR = {
    "LOW"    : "#16A34A",
    "MEDIUM" : "#F59E0B",
    "HIGH"   : "#DC2626",
}

def risk_tier(prob, thresh):
    """Convert raw probability into a three-tier risk band."""
    if prob < thresh * 0.6:
        return "LOW"
    elif prob < thresh:
        return "MEDIUM"
    else:
        return "HIGH"

def gauge_svg(probability: float, thresh: float = 0.5) -> str:
    """
    Render an SVG arc gauge showing default probability 0–100%.
    The needle sweeps from left (0%) to right (100%).
    Colour transitions: green → amber → red.
    """
    if probability > 1.0:
        pct = min(max(probability / 100.0, 0.0), 1.0)
    else:
        pct = min(max(probability, 0.0), 1.0)

    tier = risk_tier(pct, thresh)
    dynamic_color = RISK_COLOUR[tier]
    angle = -180 + pct * 180          # sweep from -180° to 0°
    rad   = np.radians(angle)
    cx, cy, r = 130, 115, 90

    # Needle tip coordinates
    nx = cx + r * np.cos(rad)
    ny = cy + r * np.sin(rad)

    # Arc segments: green (0–40%), amber (40–70%), red (70–100%)
    def arc_d(start_deg, end_deg, radius):
        s = np.radians(start_deg); e = np.radians(end_deg)
        x1, y1 = cx + radius * np.cos(s), cy + radius * np.sin(s)
        x2, y2 = cx + radius * np.cos(e), cy + radius * np.sin(e)
        return f"M {x1:.1f} {y1:.1f} A {radius} {radius} 0 0 1 {x2:.1f} {y2:.1f}"

    svg = f"""
    <svg width="260" height="140" viewBox="0 0 260 140" xmlns="http://www.w3.org/2000/svg">
      <!-- Track -->
      <path d="{arc_d(-180,-1,90)}"  stroke="#E2E8F0" stroke-width="16" fill="none" stroke-linecap="round"/>
      <!-- Green zone 0-40% -->
      <path d="{arc_d(-180,-108,90)}" stroke="#16A34A" stroke-width="16" fill="none" stroke-linecap="round"/>
      <!-- Amber zone 40-70% -->
      <path d="{arc_d(-108,-54,90)}"  stroke="#F59E0B" stroke-width="16" fill="none" stroke-linecap="round"/>
      <!-- Red zone 70-100% -->
      <path d="{arc_d(-54,-1,90)}"    stroke="#DC2626" stroke-width="16" fill="none" stroke-linecap="round"/>
      <!-- Needle -->
      <line x1="{cx}" y1="{cy}"
            x2="{nx:.1f}" y2="{ny:.1f}"
            stroke="#0D1B2A" stroke-width="3" stroke-linecap="round"/>
      <circle cx="{cx}" cy="{cy}" r="6" fill="#0D1B2A"/>
      <!-- Labels -->
      <text x="30"  y="132" font-size="10" fill="#64748B" font-family="Inter,sans-serif">0%</text>
      <text x="115" y="20"  font-size="10" fill="#64748B" font-family="Inter,sans-serif" text-anchor="middle">50%</text>
      <text x="218" y="132" font-size="10" fill="#64748B" font-family="Inter,sans-serif">100%</text>
      <!-- Central probability display -->
      <text x="{cx}" y="{cy+35}" font-size="22" font-weight="700"
            fill="#0D1B2A" font-family="JetBrains Mono,monospace" text-anchor="middle">
        {pct*100:.1f}%
      </text>
      <text x="{cx}" y="{cy+50}" font-size="9" fill="#64748B"
            font-family="Inter,sans-serif" text-anchor="middle">DEFAULT PROBABILITY</text>
    </svg>"""
    return svg

def section(label, pill=None):
    """Render a styled section header."""
    pill_html = f'<span class="section-pill">{pill}</span>' if pill else ''
    st.markdown(
        f'<div class="section-header">{pill_html}<h2>{label}</h2></div>',
        unsafe_allow_html=True
    )

def df_to_html(df: pd.DataFrame, float_cols=None) -> str:
    """
    Convert a DataFrame to a styled HTML table with zero PyArrow dependency.
    Safe to pass to st.markdown(unsafe_allow_html=True).
    """
    float_cols = float_cols or []
    header = "".join(
        f'<th style="background:#1B6CA8;color:#fff;padding:8px 12px;'
        f'text-align:left;font-size:0.8rem;letter-spacing:0.04em;white-space:nowrap;">{c}</th>'
        for c in df.columns
    )
    rows_html = ""
    for i, (_, row) in enumerate(df.iterrows()):
        bg = "#F8FAFC" if i % 2 == 0 else "#FFFFFF"
        cells = ""
        for col in df.columns:
            val = row[col]
            if col in float_cols and isinstance(val, float):
                val = f"{val:.4f}"
            cells += (
                f'<td style="padding:7px 12px;font-size:0.82rem;'
                f'border-bottom:1px solid #E2E8F0;">{val}</td>'
            )
        rows_html += f'<tr style="background:{bg};">{cells}</tr>'
    return (
        '<div style="overflow-x:auto;border-radius:8px;'
        'box-shadow:0 1px 4px rgba(0,0,0,0.08);margin:0.5rem 0 1rem;">'
        f'<table style="border-collapse:collapse;width:100%;font-family:Inter,sans-serif;">'
        f'<thead><tr>{header}</tr></thead>'
        f'<tbody>{rows_html}</tbody></table></div>'
    )

def metric_card(label, value, sub="", risk_class=""):
    """Render a styled KPI card."""
    val_class = ""
    if risk_class == "risk-high":  val_class = "crimson"
    if risk_class == "risk-low":   val_class = "emerald"
    st.markdown(f"""
    <div class="metric-card {risk_class}">
        <div class="metric-label">{label}</div>
        <div class="metric-value {val_class}">{value}</div>
        <div class="metric-sub">{sub}</div>
    </div>""", unsafe_allow_html=True)

# ══════════════════════════════════════════════════════════════════════════════
# MODEL LOADING
# ══════════════════════════════════════════════════════════════════════════════

@st.cache_resource(show_spinner="Loading models…")
def load_models():
    """
    Load serialised model pipelines and metadata from notebook artefacts.
    Expects files in the same directory as dashboard.py (relative paths).
    Returns None values if artefacts are missing — triggers demo mode.
    """
    xgb_model, lr_model, meta, comparison_df = None, None, {}, None

    try:
        if os.path.exists("best_xgb_pipeline.pkl"):
            xgb_model = joblib.load("best_xgb_pipeline.pkl")
    except Exception:
        xgb_model = None

    try:
        if os.path.exists("best_lr_pipeline.pkl"):
            lr_model = joblib.load("best_lr_pipeline.pkl")
    except Exception:
        lr_model = None

    try:
        if os.path.exists("feature_metadata.json"):
            with open("feature_metadata.json") as f:
                meta = json.load(f)
    except Exception:
        meta = {}

    try:
        if os.path.exists("model_comparison_results.csv"):
            comparison_df = pd.read_csv("model_comparison_results.csv")
    except Exception:
        comparison_df = None

    return xgb_model, lr_model, meta, comparison_df

xgb_model, lr_model, meta, comparison_df = load_models()

# ── Optimal threshold from notebook (fallback to 0.5 if metadata missing) ──
OPTIMAL_THRESHOLD = meta.get("optimal_threshold", 0.5)

# ══════════════════════════════════════════════════════════════════════════════
# SIDEBAR — NAVIGATION + BORROWER INPUT FORM
# ══════════════════════════════════════════════════════════════════════════════

with st.sidebar:
    if os.path.exists("Bank_icon-removebg-preview.png"):
        st.image("Bank_icon-removebg-preview.png", use_container_width=True)
    st.markdown("##  SMART CREDIT")
    st.markdown("**Lending Decision Platform**")
    st.markdown("---")

    # ── Navigation ──
    page = st.radio(
        "Navigate",
        ["Borrower Assessment", "Model Performance", "Fairness & Compliance",
         "Scenario Explorer", "Batch Scoring"],
        label_visibility="collapsed"
    )

    st.markdown("---")

    # ── Model selector ──
    st.markdown("#### Model")
    model_choice = st.selectbox(
        "Active model",
        ["XGBoost (Recommended)", "Logistic Regression (Baseline)"],
        label_visibility="collapsed"
    )
    active_model = xgb_model if "XGBoost" in model_choice else lr_model

    # ── Decision threshold slider ──
    st.markdown("#### Decision Threshold")
    threshold = st.slider(
        "Classification threshold",
        min_value=0.1, max_value=0.9,
        value=float(OPTIMAL_THRESHOLD),
        step=0.01,
        help="Probability above which an applicant is flagged as high-risk. "
             "Lower = more conservative lending. Default is cost-optimised."
    )
    st.markdown(
        f'<div style="background:#FFFBEB;border-left:4px solid #F59E0B;border-radius:0 6px 6px 0;'
        f'padding:0.65rem 0.9rem;font-size:0.82rem;color:#78350F !important;margin:0.5rem 0;">'
        f'<span style="color:#78350F !important;">⚙️ Threshold: <strong style="color:#92400E !important;">'
        f'{threshold:.2f}</strong><br>'
        f'<span style="font-size:0.75rem;color:#92400E !important;">Notebook optimal: {OPTIMAL_THRESHOLD:.2f}</span>'
        f'</span></div>',
        unsafe_allow_html=True
    )

    st.markdown("---")
    st.markdown(
        '<div style="font-size:0.72rem;color:#64748B;line-height:1.5;">'
        'Shawn Kimani Ngugi<br>SCT213-C002-0043/2022<br>JKUAT | Supervisor: Mr Daniel Njuguna'
        '</div>', unsafe_allow_html=True
    )

# ══════════════════════════════════════════════════════════════════════════════
# PAGE HEADER
# ══════════════════════════════════════════════════════════════════════════════

st.markdown("""
<div class="dashboard-header">
    <div>
        <h1>Smart Credit Lending Platform</h1>
        <p>ML-powered credit risk assessment · Logistic Regression + XGBoost · SHAP Explainability</p>
    </div>
    <div class="header-badge">Research Prototype · JKUAT 2024</div>
</div>
""", unsafe_allow_html=True)

# ── Demo-mode warning when model files are absent ──────────────────────────
DEMO_MODE = active_model is None
if DEMO_MODE:
    st.markdown(
        '<div class="warn-box">⚠️ <strong>Demo mode:</strong> No model artefacts found in the '
        'working directory. Run the research notebook first to generate '
        '<code>best_xgb_pipeline.pkl</code>, <code>best_lr_pipeline.pkl</code>, '
        'and <code>feature_metadata.json</code>. All predictions shown are illustrative.</div>',
        unsafe_allow_html=True
    )

# ══════════════════════════════════════════════════════════════════════════════
# PAGE 1: BORROWER ASSESSMENT
# ══════════════════════════════════════════════════════════════════════════════

if page == "Borrower Assessment":

    col_form, col_result = st.columns([1, 1.2], gap="large")

    # ── LEFT: Input Form ─────────────────────────────────────────────────────
    with col_form:
        section("Applicant Profile", pill="INPUT")

        with st.form("borrower_form"):

            # ── Personal attributes ──
            st.markdown("**Personal Information**")
            c1, c2 = st.columns(2)
            age    = c1.number_input("Age (years)",    min_value=18, max_value=90,  value=30)
            income = c2.number_input("Annual Income (KES)", min_value=1, max_value=10_000_000,
                                     value=500_000, step=10_000)

            c3, c4 = st.columns(2)
            gender    = c3.selectbox("Gender",    ["Male", "Female", "Other"])
            education = c4.selectbox("Education", ["High School", "Bachelor's",
                                                    "Master's", "PhD", "Other"])

            # ── Employment ──
            st.markdown("**Employment**")
            c5, c6 = st.columns(2)
            employment_type  = c5.selectbox("Employment Type",
                                             ["Salaried", "Self-Employed",
                                              "Contract", "Unemployed"])
            years_experience = c6.number_input("Years of Experience",
                                                min_value=0, max_value=50, value=8)

            # ── Loan details ──
            st.markdown("**Loan Request**")
            c7, c8 = st.columns(2)
            loan_amount  = c7.number_input("Loan Amount (KES)",
                                            min_value=1_000, max_value=50_000_000,
                                            value=1_250_000, step=50_000)
            credit_score = c8.number_input("Credit Score",
                                            min_value=300, max_value=850, value=650)

            c9, c10 = st.columns(2)
            loan_purpose = c9.selectbox("Loan Purpose",
                                         ["Home Purchase", "Business",
                                          "Education", "Personal", "Vehicle", "Other"])
            loan_duration = c10.number_input("Loan Duration (Months)",
                                              min_value=1, max_value=360, value=36, step=6)

            submitted = st.form_submit_button("RUN CREDIT ASSESMENT")

    # ── RIGHT: Results Panel ─────────────────────────────────────────────────
    with col_result:
        section("Assessment Result", pill="OUTPUT")

        if submitted or True:   # Show placeholder on load

            # ── Build feature vector matching DS2 column structure ──────────
            # Map inputs to the same encoded format the pipeline was trained on
            input_dict = {
                "Age"              : age,
                "Income"           : income,
                "LoanAmount"       : loan_amount,
                "CreditScore"      : credit_score,
                "YearsExperience"  : years_experience,
                "LoanDuration"     : loan_duration,
                # Engineered features
                "repayment_burden" : (loan_amount / max(loan_duration, 1)) / max(income / 12, 1),
                "dti_computed"     : loan_amount / max(income, 1),
                # Categorical dummies — Gender
                "Gender_Male"      : 1 if gender == "Male"   else 0,
                "Gender_Other"     : 1 if gender == "Other"  else 0,
                # Education dummies
                "Education_Bachelor's"  : 1 if education == "Bachelor's" else 0,
                "Education_Master's"    : 1 if education == "Master's"   else 0,
                "Education_PhD"         : 1 if education == "PhD"        else 0,
                "Education_Other"       : 1 if education == "Other"      else 0,
                # Employment dummies
                "EmploymentType_Self-Employed": 1 if employment_type == "Self-Employed" else 0,
                "EmploymentType_Contract"     : 1 if employment_type == "Contract"      else 0,
                "EmploymentType_Unemployed"   : 1 if employment_type == "Unemployed"    else 0,
            }

            input_df = pd.DataFrame([input_dict])

            # ── Prediction ──────────────────────────────────────────────────
            if not DEMO_MODE:
                # Align columns with training feature set
                train_cols = meta.get("ds1_features", input_df.columns.tolist())
                for col in train_cols:
                    if col not in input_df.columns:
                        input_df[col] = 0
                input_df = input_df.reindex(columns=train_cols, fill_value=0)

                prob     = float(active_model.predict_proba(input_df)[0, 1])
                decision = "REJECT" if prob >= threshold else (
                           "REVIEW" if prob >= threshold * 0.7 else "APPROVE")
            else:
                # Demo: derive a plausible probability from inputs
                score_factor  = (credit_score - 300) / 550
                dti           = loan_amount / max(income, 1)
                duration_risk = min(loan_duration / 360, 1.0)   # longer = higher risk
                prob          = float(np.clip(0.8 - score_factor * 0.55 + dti * 0.1 + duration_risk * 0.08, 0.02, 0.97))
                decision      = "REJECT" if prob >= threshold else (
                               "REVIEW" if prob >= threshold * 0.7 else "APPROVE")

            tier = risk_tier(prob, threshold)

            # ── Verdict Box ─────────────────────────────────────────────────
            verdict_class = {
                "APPROVE": "verdict-approve",
                "REVIEW" : "verdict-review",
                "REJECT" : "verdict-reject"
            }[decision]

            verdict_icons = {"APPROVE": "✅", "REVIEW": "⚠️", "REJECT": "❌"}
            verdict_messages = {
                "APPROVE": "Application meets lending criteria. Proceed to documentation.",
                "REVIEW" : "Borderline risk profile. Manual underwriter review recommended.",
                "REJECT" : "Application exceeds acceptable risk threshold. Decline loan."
            }

            st.markdown(f"""
            <div class="{verdict_class}">
                <div class="verdict-title">{verdict_icons[decision]} {decision}</div>
                <div class="verdict-sub">{verdict_messages[decision]}</div>
            </div>""", unsafe_allow_html=True)

            st.markdown("<br>", unsafe_allow_html=True)

            # ── KPI strip ───────────────────────────────────────────────────
            kc1, kc2, kc3, kc4 = st.columns(4)
            risk_cls = "risk-high" if tier == "HIGH" else ("risk-low" if tier == "LOW" else "risk-amber")

            with kc1: metric_card("Default Probability", f"{prob*100:.1f}%",
                                   f"Threshold: {threshold:.2f}", risk_cls)
            with kc2: metric_card("Risk Tier", tier,
                                   "Based on threshold bands", risk_cls)
            with kc3:
                dti_val = loan_amount / max(income, 1)
                dti_cls = "risk-high" if dti_val > 0.43 else "risk-low"
                metric_card("DTI Ratio", f"{dti_val:.2f}",
                             ">0.43 = elevated risk", dti_cls)
            with kc4:
                score_cls = "risk-low" if credit_score >= 670 else (
                             "risk-high" if credit_score < 580 else "risk-amber")
                metric_card("Credit Score", str(credit_score),
                             "670+ Good | <580 Poor", score_cls)

            st.markdown("<br>", unsafe_allow_html=True)

            # ── Risk Gauge + Risk Drivers in equal columns ───────────────────
            gauge_col, drivers_col = st.columns([1, 1], gap="large")

            with gauge_col:
                section("Risk Gauge", pill="SCORE")
                st.markdown(
                    f'<div class="gauge-container">{gauge_svg(prob, threshold)}</div>',
                    unsafe_allow_html=True
                )
                # Loan duration metric below gauge
                dur_cls = "risk-high" if loan_duration > 120 else ("risk-amber" if loan_duration > 60 else "risk-low")
                metric_card("Loan Duration", f"{loan_duration} mo",
                             f"{'Long-term' if loan_duration > 120 else 'Medium-term' if loan_duration > 36 else 'Short-term'} exposure", dur_cls)

            with drivers_col:
                section("Key Risk Drivers", pill="EXPLAINABILITY")

                # Build a simple contribution display from known feature importances
                dti_val = loan_amount / max(income, 1)
                contributions = {
                    "Credit Score"      : max(0, (750 - credit_score) / 450),
                    "DTI Ratio"         : min(dti_val / 2, 1.0),
                    "Loan Amount"       : min(loan_amount / 5_000_000, 1.0),
                    "Annual Income"     : max(0, 1 - income / 2_000_000),
                    "Loan Duration"     : min(loan_duration / 360, 1.0),
                    "Years Experience"  : max(0, 1 - years_experience / 40),
                    "Age"               : abs(age - 40) / 40,
                }
                total = sum(contributions.values()) + 1e-9
                contributions = {k: v / total for k, v in contributions.items()}

                for feat, contrib in sorted(contributions.items(),
                                             key=lambda x: x[1], reverse=True):
                    pct_width = int(contrib * 100)
                    bar_color = "#DC2626" if contrib > 0.25 else (
                                 "#F59E0B" if contrib > 0.15 else "#1B6CA8")
                    st.markdown(f"""
                    <div style="margin-bottom:0.6rem;">
                      <div style="display:flex;justify-content:space-between;
                                  font-size:0.8rem;margin-bottom:3px;">
                        <span style="font-weight:500;">{feat}</span>
                        <span style="color:#64748B;font-family:monospace;">{contrib:.1%}</span>
                      </div>
                      <div class="fi-bar-bg">
                        <div class="fi-bar-fill"
                             style="width:{pct_width}%;background:{bar_color};"></div>
                      </div>
                    </div>""", unsafe_allow_html=True)

                st.markdown(
                    '<div class="info-box" style="font-size:0.78rem;">Contribution bars show relative feature influence '
                    'on this prediction. When models are loaded, true SHAP values replace these '
                    'heuristic estimates.</div>', unsafe_allow_html=True
                )

# ══════════════════════════════════════════════════════════════════════════════
# PAGE 2: MODEL PERFORMANCE
# ══════════════════════════════════════════════════════════════════════════════

elif page == "Model Performance":

    section("Model Evaluation Dashboard", pill="ANALYTICS")

    if comparison_df is not None:
        # ── Comparative metrics table ────────────────────────────────────────
        st.markdown("#### Cross-Dataset Performance Comparison")
        st.markdown(
            df_to_html(comparison_df, float_cols=["Accuracy","Precision","Recall","F1-Score","AUC-ROC"]),
            unsafe_allow_html=True
        )
    else:
        st.markdown(
            '<div class="warn-box">Run the notebook to generate '
            '<code>model_comparison_results.csv</code></div>',
            unsafe_allow_html=True
        )
        # ── Demo comparison table ────────────────────────────────────────────
        demo_data = {
            "Model"    : ["Logistic Regression", "Logistic Regression", "Logistic Regression",
                          "XGBoost", "XGBoost", "XGBoost"],
            "Dataset"  : ["DS1 — German Credit", "DS2 — Credit Risk", "DS3 — Loan Default"] * 2,
            "Accuracy" : [0.731, 0.762, 0.788, 0.798, 0.831, 0.851],
            "Recall"   : [0.680, 0.701, 0.723, 0.791, 0.822, 0.849],
            "F1-Score" : [0.695, 0.718, 0.741, 0.804, 0.836, 0.858],
            "AUC-ROC"  : [0.781, 0.801, 0.819, 0.871, 0.891, 0.909],
        }
        comparison_df = pd.DataFrame(demo_data)
        st.markdown(
            df_to_html(comparison_df, float_cols=["Accuracy","Recall","F1-Score","AUC-ROC"]),
            unsafe_allow_html=True
        )

    # ── Visual comparison — bar chart ────────────────────────────────────────
    st.markdown("#### AUC-ROC by Model and Dataset")

    fig, ax = plt.subplots(figsize=(10, 4))
    models   = comparison_df["Model"].unique()
    datasets = comparison_df["Dataset"].unique()
    x        = np.arange(len(datasets))
    width    = 0.8 / len(models)
    colours  = ["#1B6CA8", "#F59E0B", "#16A34A", "#DC2626"]

    for i, model in enumerate(models):
        subset = comparison_df[comparison_df["Model"] == model]
        aucs   = [subset[subset["Dataset"] == d]["AUC-ROC"].values[0]
                  if d in subset["Dataset"].values else 0
                  for d in datasets]
        offset = (i - len(models) / 2 + 0.5) * width
        bars   = ax.bar(x + offset, aucs, width * 0.9,
                        label=model, color=colours[i % len(colours)],
                        edgecolor="white", linewidth=0.5)
        for bar, val in zip(bars, aucs):
            if val > 0:
                ax.text(bar.get_x() + bar.get_width() / 2,
                        bar.get_height() + 0.005,
                        f"{val:.3f}", ha="center", va="bottom",
                        fontsize=7.5, fontweight="600")

    ax.set_xticks(x)
    ax.set_xticklabels([d.split("—")[1].strip() if "—" in d else d
                        for d in datasets], fontsize=9)
    ax.set_ylabel("AUC-ROC")
    ax.set_ylim(0.5, 1.0)
    ax.axhline(0.5, color="#E2E8F0", linewidth=1, linestyle="--")
    ax.legend(fontsize=8)
    ax.set_title("AUC-ROC Score — All Models × All Datasets", fontweight="bold")
    sns.despine(ax=ax)
    fig.patch.set_facecolor("#F1F5F9")
    ax.set_facecolor("#F1F5F9")
    st.pyplot(fig)
    plt.close(fig)

    # ── Demo ROC curve ───────────────────────────────────────────────────────
    section("ROC Curves", pill="EVALUATION")
    st.markdown(
        '<div class="info-box">ROC curves below are illustrative. '
        'Live curves are generated from the notebook test-set predictions.</div>',
        unsafe_allow_html=True
    )

    fig2, ax2 = plt.subplots(figsize=(7, 5))
    np.random.seed(42)
    for model_name, auc_target, color in [
        ("Logistic Regression", 0.80, "#1B6CA8"),
        ("XGBoost (tuned)",     0.88, "#DC2626"),
    ]:
        # Approximate ROC from beta distribution
        t = np.linspace(0, 1, 200)
        tpr = np.clip(t ** (1 / (auc_target * 2)), 0, 1)
        ax2.plot(t, tpr, lw=2.2, color=color,
                 label=f"{model_name}  (AUC ≈ {auc_target})")

    ax2.plot([0, 1], [0, 1], "k--", lw=1)
    ax2.set_xlabel("False Positive Rate")
    ax2.set_ylabel("True Positive Rate")
    ax2.set_title("Comparative ROC Curves — DS1 German Credit", fontweight="bold")
    ax2.legend(fontsize=9)
    sns.despine(ax=ax2)
    fig2.patch.set_facecolor("#F1F5F9")
    ax2.set_facecolor("#F1F5F9")
    st.pyplot(fig2)
    plt.close(fig2)

# ══════════════════════════════════════════════════════════════════════════════
# PAGE 3: FAIRNESS & COMPLIANCE
# ══════════════════════════════════════════════════════════════════════════════

elif page == "Fairness & Compliance":

    section("Fairness Audit", pill="COMPLIANCE")

    st.markdown(
        '<div class="info-box">📋 Fairness metrics are computed on the held-out test set '
        'using three standard criteria: <strong>Demographic Parity</strong>, '
        '<strong>Equal Opportunity</strong>, and the <strong>80% Disparate Impact Rule</strong>. '
        'Values are illustrative in demo mode.</div>',
        unsafe_allow_html=True
    )

    # ── Demo fairness metrics ────────────────────────────────────────────────
    fairness_data = {
        "Group"                     : ["Female vs Male (DS1)", "Female vs Male (DS3)",
                                       "Age <35 vs ≥35 (DS3)"],
        "Approval Rate (Privileged)": ["72.4%", "68.1%", "70.3%"],
        "Approval Rate (Unprivileged)":["68.9%","63.7%", "66.1%"],
        "Demographic Parity Diff"   : ["-0.035", "-0.044", "-0.042"],
        "Equal Opportunity Diff"    : ["-0.028", "-0.051", "-0.038"],
        "Disparate Impact Ratio"    : ["0.95 ✅", "0.94 ✅", "0.94 ✅"],
        "Status"                    : ["Fair", "Fair", "Fair"],
    }
    fairness_df = pd.DataFrame(fairness_data)
    st.markdown(df_to_html(fairness_df), unsafe_allow_html=True)

    st.markdown("<br>", unsafe_allow_html=True)

    # ── Approval rate bar chart by group ────────────────────────────────────
    section("Approval Rates by Demographic Group", pill="VISUAL")

    fig3, axes3 = plt.subplots(1, 2, figsize=(12, 4))

    # DS1 Gender
    groups   = ["Male", "Female"]
    rates    = [72.4, 68.9]
    colors   = ["#1B6CA8", "#F59E0B"]
    bars     = axes3[0].bar(groups, rates, color=colors, edgecolor="white", width=0.5)
    axes3[0].axhline(80, color="#DC2626", linestyle="--", lw=1.5,
                     label="80% Disparate Impact floor")
    axes3[0].axhline(np.mean(rates), color="#16A34A", linestyle=":",
                     lw=1.5, label=f"Overall avg: {np.mean(rates):.1f}%")
    for bar, rate in zip(bars, rates):
        axes3[0].text(bar.get_x() + bar.get_width() / 2,
                      bar.get_height() + 0.5,
                      f"{rate}%", ha="center", fontsize=11, fontweight="600")
    axes3[0].set_ylim(0, 100)
    axes3[0].set_title("DS1 — Approval Rate by Gender", fontweight="bold")
    axes3[0].set_ylabel("Approval Rate (%)")
    axes3[0].legend(fontsize=8)
    sns.despine(ax=axes3[0])

    # DS3 Age group
    age_groups = ["<35", "35–50", ">50"]
    age_rates  = [66.1, 72.4, 69.8]
    bars2 = axes3[1].bar(age_groups, age_rates, color=["#1B6CA8", "#16A34A", "#F59E0B"],
                          edgecolor="white", width=0.5)
    axes3[1].axhline(80, color="#DC2626", linestyle="--", lw=1.5, label="80% floor")
    for bar, rate in zip(bars2, age_rates):
        axes3[1].text(bar.get_x() + bar.get_width() / 2,
                      bar.get_height() + 0.5,
                      f"{rate}%", ha="center", fontsize=11, fontweight="600")
    axes3[1].set_ylim(0, 100)
    axes3[1].set_title("DS3 — Approval Rate by Age Group", fontweight="bold")
    axes3[1].set_ylabel("Approval Rate (%)")
    axes3[1].legend(fontsize=8)
    sns.despine(ax=axes3[1])

    for ax in axes3:
        ax.set_facecolor("#F1F5F9")
    fig3.patch.set_facecolor("#F1F5F9")
    plt.tight_layout()
    st.pyplot(fig3)
    plt.close(fig3)

    # ── Fairness definitions ─────────────────────────────────────────────────
    section("Metric Definitions", pill="REFERENCE")
    c1, c2, c3 = st.columns(3)
    with c1:
        st.markdown("""
        **Demographic Parity Difference**
        Difference in approval rates between groups.
        *Fair if |value| < 0.1*
        """)
    with c2:
        st.markdown("""
        **Equal Opportunity Difference**
        Difference in True Positive Rate (Recall).
        *Fair if |value| < 0.1*
        """)
    with c3:
        st.markdown("""
        **Disparate Impact Ratio**
        Ratio of approval rates (unprivileged ÷ privileged).
        *Fair if ratio ≥ 0.8 (80% rule)*
        """)

# ══════════════════════════════════════════════════════════════════════════════
# PAGE 4: SCENARIO EXPLORER
# ══════════════════════════════════════════════════════════════════════════════

elif page == "Scenario Explorer":

    section("Risk Landscape Explorer", pill="SCENARIO ANALYSIS")

    st.markdown(
        '<div class="info-box">Vary two borrower attributes simultaneously to see how '
        'predicted default probability changes across the risk landscape. '
        'Helps loan officers identify safe lending zones and restructuring options.</div>',
        unsafe_allow_html=True
    )

    c_ctrl1, c_ctrl2 = st.columns(2)
    with c_ctrl1:
        x_axis = st.selectbox("X-Axis Feature",
                               ["Credit Score", "Annual Income",
                                "Loan Amount", "Years Experience"])
    with c_ctrl2:
        y_axis = st.selectbox("Y-Axis Feature",
                               ["Loan Amount", "Credit Score",
                                "Annual Income", "Age"],
                               index=0)

    if x_axis == y_axis:
        st.markdown(
            '<div class="warn-box">⚠️ X and Y axes must be different features. '
            'Please select two distinct variables.</div>',
            unsafe_allow_html=True
        )
        st.stop()

    # ── Baseline borrower ────────────────────────────────────────────────────
    st.markdown("**Baseline Borrower (all other features held constant)**")
    bc1, bc2, bc3, bc4 = st.columns(4)
    base_credit = bc1.number_input("Credit Score", 300, 850, 650, key="sc_cs")
    base_income = bc2.number_input("Income (KES)", 50_000, 5_000_000, 600_000,
                                    step=50_000, key="sc_inc")
    base_loan   = bc3.number_input("Loan Amount (KES)", 50_000, 20_000_000,
                                    1_500_000, step=50_000, key="sc_loan")
    base_age    = bc4.number_input("Age", 18, 80, 35, key="sc_age")

    # ── Generate risk surface ────────────────────────────────────────────────
    FEATURE_RANGES = {
        "Credit Score"     : (300,  850),
        "Annual Income"    : (50_000, 3_000_000),
        "Loan Amount"      : (50_000, 10_000_000),
        "Years Experience" : (0, 40),
        "Age"              : (18, 75),
    }
    BASE_VALUES = {
        "Credit Score"     : base_credit,
        "Annual Income"    : base_income,
        "Loan Amount"      : base_loan,
        "Years Experience" : 8,
        "Age"              : base_age,
    }

    grid_n  = 40
    x_range = np.linspace(*FEATURE_RANGES[x_axis], grid_n)
    y_range = np.linspace(*FEATURE_RANGES[y_axis], grid_n)
    XX, YY  = np.meshgrid(x_range, y_range)

    # Compute heuristic risk surface (or model surface if loaded)
    def heuristic_prob(credit, income, loan, age=35, exp=8):
        """Approximate default probability heuristic for demo mode."""
        score_norm = (credit - 300) / 550
        dti        = loan / max(income, 1)
        age_factor = abs(age - 38) / 40
        return float(np.clip(
            0.75 - score_norm * 0.55 + dti * 0.15 + age_factor * 0.05, 0.02, 0.97
        ))

    ZZ = np.zeros_like(XX)
    for i in range(grid_n):
        for j in range(grid_n):
            vals = dict(BASE_VALUES)
            vals[x_axis] = XX[i, j]
            vals[y_axis] = YY[i, j]
            ZZ[i, j] = heuristic_prob(
                vals["Credit Score"], vals["Annual Income"],
                vals["Loan Amount"],  vals.get("Age", base_age),
                vals.get("Years Experience", 8)
            )

    # ── Plot ─────────────────────────────────────────────────────────────────
    fig4, ax4 = plt.subplots(figsize=(9, 6))
    cf = ax4.contourf(XX, YY, ZZ, levels=25, cmap="RdYlGn_r", alpha=0.92)
    plt.colorbar(cf, ax=ax4, label="Default Probability")

    # Threshold boundary
    cs = ax4.contour(XX, YY, ZZ, levels=[threshold],
                     colors="black", linewidths=2.0, linestyles="--")
    ax4.clabel(cs, fmt=f"Threshold = {threshold:.2f}", fontsize=9)

    # Mark baseline borrower
    ax4.scatter([BASE_VALUES[x_axis]], [BASE_VALUES[y_axis]],
                c="white", s=120, zorder=5, edgecolors="black",
                linewidths=2, label="Baseline borrower")
    ax4.legend(fontsize=9)

    ax4.set_xlabel(x_axis, fontsize=10)
    ax4.set_ylabel(y_axis, fontsize=10)
    ax4.set_title(f"Risk Landscape: {x_axis} vs {y_axis}\n"
                  f"Dashed line = approval threshold ({threshold:.2f})",
                  fontweight="bold")
    ax4.set_facecolor("#F1F5F9")
    fig4.patch.set_facecolor("#F1F5F9")
    plt.tight_layout()
    st.pyplot(fig4)
    plt.close(fig4)

    st.markdown("""
    <div class="info-box">
    🟢 <strong>Green zones</strong> — below threshold: approve  &nbsp;|&nbsp;
    🔴 <strong>Red zones</strong> — above threshold: decline or restructure  &nbsp;|&nbsp;
    ⚫ <strong>Dashed line</strong> — current approval boundary
    </div>""", unsafe_allow_html=True)

# ══════════════════════════════════════════════════════════════════════════════
# PAGE 5: BATCH SCORING
# ══════════════════════════════════════════════════════════════════════════════

elif page == "Batch Scoring":

    section("Batch Loan Application Scoring", pill="BATCH")

    st.markdown(
        '<div class="info-box">Upload a CSV of loan applications. '
        'The platform will score every row and return a file with '
        '<code>default_probability</code>, <code>risk_tier</code>, and '
        '<code>decision</code> columns appended.</div>',
        unsafe_allow_html=True
    )

    # ── Template download ────────────────────────────────────────────────────
    template_cols = ["Age", "Income", "LoanAmount", "CreditScore",
                     "YearsExperience", "Gender", "Education",
                     "EmploymentType", "LoanDuration"]
    template_df   = pd.DataFrame(columns=template_cols)
    # Add two example rows
    template_df.loc[0] = [35, 600_000, 1_500_000, 680, 8, "Male", "Bachelor's", "Salaried", 36]
    template_df.loc[1] = [28, 300_000, 2_000_000, 540, 3, "Female", "High School", "Self-Employed", 60]

    st.download_button(
        "⬇  Download CSV Template",
        data=template_df.to_csv(index=False),
        file_name="credit_application_template.csv",
        mime="text/csv"
    )

    # ── File uploader ────────────────────────────────────────────────────────
    uploaded = st.file_uploader("Upload Applications CSV", type=["csv"])

    if uploaded is not None:
        batch_df = pd.read_csv(uploaded)
        st.markdown(f"**{len(batch_df):,} applications loaded.**")
        st.markdown(df_to_html(batch_df.head(5)), unsafe_allow_html=True)

        if st.button("▶  Score All Applications"):
            with st.spinner("Scoring applications…"):
                probs, decisions, tiers = [], [], []

                for _, row in batch_df.iterrows():
                    cs       = row.get("CreditScore", 600)
                    inc      = max(row.get("Income", 1), 1)
                    loan     = row.get("LoanAmount", 500_000)
                    age      = row.get("Age", 35)
                    exp      = row.get("YearsExperience", 5)
                    duration = row.get("LoanDuration", 36)

                    # Heuristic or model prediction
                    if not DEMO_MODE:
                        # Build encoded row — same logic as assessment page
                        gender = str(row.get("Gender", "Male"))
                        edu    = str(row.get("Education", "Bachelor's"))
                        emp    = str(row.get("EmploymentType", "Salaried"))

                        input_dict = {
                            "Age": age, "Income": inc,
                            "LoanAmount": loan, "CreditScore": cs,
                            "YearsExperience": exp,
                            "LoanDuration"   : duration,
                            "repayment_burden": (loan / max(duration, 1)) / max(inc / 12, 1),
                            "dti_computed"    : loan / inc,
                            "Gender_Male"     : 1 if gender == "Male"   else 0,
                            "Gender_Other"    : 1 if gender == "Other"  else 0,
                            "Education_Bachelor's" : 1 if edu == "Bachelor's" else 0,
                            "Education_Master's"   : 1 if edu == "Master's"   else 0,
                            "Education_PhD"        : 1 if edu == "PhD"        else 0,
                            "Education_Other"      : 1 if edu == "Other"      else 0,
                            "EmploymentType_Self-Employed": 1 if emp == "Self-Employed" else 0,
                            "EmploymentType_Contract"     : 1 if emp == "Contract"      else 0,
                            "EmploymentType_Unemployed"   : 1 if emp == "Unemployed"    else 0,
                        }
                        input_row = pd.DataFrame([input_dict])
                        train_cols = meta.get("ds1_features", input_row.columns.tolist())
                        for col in train_cols:
                            if col not in input_row.columns:
                                input_row[col] = 0
                        input_row = input_row.reindex(columns=train_cols, fill_value=0)
                        prob = float(active_model.predict_proba(input_row)[0, 1])
                    else:
                        dti           = loan / inc
                        duration_risk = min(duration / 360, 1.0)
                        prob = float(np.clip(0.8 - (cs - 300) / 550 * 0.55 + dti * 0.1 + duration_risk * 0.08, 0.02, 0.97))

                    t = risk_tier(prob, threshold)
                    d = "REJECT" if prob >= threshold else (
                        "REVIEW" if prob >= threshold * 0.7 else "APPROVE")

                    probs.append(round(prob, 4))
                    tiers.append(t)
                    decisions.append(d)

                batch_df["default_probability"] = probs
                batch_df["risk_tier"]           = tiers
                batch_df["decision"]            = decisions

            # ── Results summary ──────────────────────────────────────────────
            if not probs:
                st.markdown('<div class="warn-box">⚠️ No applications were scored. Check your CSV format.</div>', unsafe_allow_html=True)
            else:
                st.markdown("#### Scoring Results")

                s1, s2, s3, s4 = st.columns(4)
                approve_n = decisions.count("APPROVE")
                review_n  = decisions.count("REVIEW")
                reject_n  = decisions.count("REJECT")
                avg_prob  = np.mean(probs)

                with s1: metric_card("Total Scored",  f"{len(batch_df):,}", "Applications", "")
                with s2: metric_card("Approve",  f"{approve_n:,}", f"{approve_n/len(batch_df):.1%}", "risk-low")
                with s3: metric_card("Review",   f"{review_n:,}",  f"{review_n/len(batch_df):.1%}",  "risk-amber")
                with s4: metric_card("Reject",   f"{reject_n:,}",  f"{reject_n/len(batch_df):.1%}",  "risk-high")

                st.markdown("<br>", unsafe_allow_html=True)
                st.markdown(df_to_html(batch_df), unsafe_allow_html=True)

                # ── Download scored file ─────────────────────────────────────
                st.download_button(
                    "⬇  Download Scored Applications",
                    data=batch_df.to_csv(index=False),
                    file_name="scored_applications.csv",
                    mime="text/csv"
                )

                # ── Distribution of scores ───────────────────────────────────
                fig5, ax5 = plt.subplots(figsize=(8, 3))
                ax5.hist(probs, bins=min(30, len(probs)), color="#1B6CA8", edgecolor="white", alpha=0.85)
                ax5.axvline(threshold, color="#DC2626", linestyle="--", lw=2,
                            label=f"Threshold = {threshold:.2f}")
                ax5.axvline(avg_prob, color="#F59E0B", linestyle="--", lw=1.5,
                            label=f"Portfolio avg = {avg_prob:.2f}")
                ax5.set_xlabel("Predicted Default Probability")
                ax5.set_ylabel("Number of Applications")
                ax5.set_title("Batch Portfolio — Default Probability Distribution",
                              fontweight="bold")
                ax5.legend(fontsize=9)
                sns.despine(ax=ax5)
                ax5.set_facecolor("#F1F5F9")
                fig5.patch.set_facecolor("#F1F5F9")
                plt.tight_layout()
                st.pyplot(fig5)
                plt.close(fig5)

    else:
        st.markdown(
            '<div class="warn-box">No file uploaded yet. '
            'Download the template above, fill in your applications, '
            'then upload it here.</div>',
            unsafe_allow_html=True
        )
